/**
 * 「あなたに合うOSS診断」MVP対象データ
 *
 * 対象は5 SaaS × ossalt.jp掲載データ上の代替候補（primary_competitor が
 * 一致するアーカイブ済みでないツール）。ここに列挙したtoolIdは、必ず
 * data-source/tools.json に実在するidであること（テストで検証する）。
 *
 * 各項目の値は、公開されている製品ドキュメント・リポジトリの記載を
 * 手作業で確認したもの。確認できなかった項目は "unknown" のままにし、
 * 推測では埋めていない。ライセンス・スター数・健全度など、すでに
 * ossalt.jp本体のデータにある項目はここには複製しない。
 */
import type { SaasId, ToolDiagnosisMeta } from "./diagnosis-types.ts";

export const TOOL_DIAGNOSIS: Record<string, ToolDiagnosisMeta> = {
  // ---------------- Notion ----------------
  appflowy: {
    toolId: "appflowy",
    saas: "notion",
    selfHost: true,
    managedCloud: true, // AppFlowy Cloud
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small", "medium"],
    strengths: ["privacy", "customization", "active"],
    features: {
      docs: true,
      wiki: true,
      database: true,
      realtimeCollaboration: true,
      mobile: true,
      api: "unknown",
      fileAttachment: true,
      permissions: "unknown",
    },
  },
  affine: {
    toolId: "affine",
    saas: "notion",
    selfHost: true,
    managedCloud: true, // AFFiNE Cloud
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small", "medium"],
    strengths: ["privacy", "usability", "customization", "active"],
    features: {
      docs: true,
      wiki: true,
      database: true,
      realtimeCollaboration: true,
      mobile: true,
      api: "unknown",
      fileAttachment: true,
      permissions: "unknown",
    },
  },
  siyuan: {
    toolId: "siyuan",
    saas: "notion",
    selfHost: true,
    managedCloud: "unknown",
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small"],
    strengths: ["privacy", "customization"],
    features: {
      docs: true,
      wiki: true,
      database: "unknown",
      realtimeCollaboration: "unknown",
      mobile: true,
      api: true,
      fileAttachment: true,
      permissions: "unknown",
    },
  },
  docmost: {
    toolId: "docmost",
    saas: "notion",
    selfHost: true,
    managedCloud: "unknown",
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small", "medium"],
    strengths: ["privacy", "usability", "cost"],
    features: {
      docs: true,
      wiki: true,
      database: false,
      realtimeCollaboration: true,
      mobile: false,
      api: "unknown",
      fileAttachment: true,
      permissions: true,
    },
  },
  anytype: {
    toolId: "anytype",
    saas: "notion",
    selfHost: true,
    managedCloud: true, // Anytypeの同期ネットワーク
    technicalLevel: 2,
    maintenanceLevel: 2,
    teamSize: ["solo", "small"],
    strengths: ["privacy", "security", "customization"],
    features: {
      docs: true,
      wiki: "unknown",
      database: true,
      realtimeCollaboration: "unknown",
      mobile: true,
      api: "unknown",
      fileAttachment: true,
      permissions: "unknown",
    },
  },

  // ---------------- Slack ----------------
  "rocket-chat": {
    toolId: "rocket-chat",
    saas: "slack",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 2,
    teamSize: ["small", "medium", "large"],
    strengths: ["customization", "features", "security"],
    features: {
      chat: true,
      threads: true,
      fileSharing: true,
      search: true,
      notifications: true,
      mobile: true,
      sso: true,
      voiceVideo: true,
    },
  },
  mattermost: {
    toolId: "mattermost",
    saas: "slack",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 2,
    teamSize: ["small", "medium", "large"],
    strengths: ["security", "features", "active"],
    features: {
      chat: true,
      threads: true,
      fileSharing: true,
      search: true,
      notifications: true,
      mobile: true,
      sso: true,
      voiceVideo: "unknown",
    },
  },
  zulip: {
    toolId: "zulip",
    saas: "slack",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 2,
    teamSize: ["small", "medium", "large"],
    strengths: ["usability", "active", "cost"],
    features: {
      chat: true,
      threads: true, // トピック単位のスレッド構造が特徴
      fileSharing: true,
      search: true,
      notifications: true,
      mobile: true,
      sso: true,
      voiceVideo: "unknown",
    },
  },
  element: {
    toolId: "element",
    saas: "slack",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 2,
    maintenanceLevel: 2,
    teamSize: ["small", "medium", "large"],
    strengths: ["security", "privacy", "customization"],
    features: {
      chat: true,
      threads: true,
      fileSharing: true,
      search: true,
      notifications: true,
      mobile: true,
      sso: "unknown",
      voiceVideo: true,
    },
  },
  synapse: {
    toolId: "synapse",
    saas: "slack",
    selfHost: true,
    managedCloud: "unknown",
    technicalLevel: 3, // Matrixホームサーバー自体の運用は難易度が高い
    maintenanceLevel: 3,
    teamSize: ["medium", "large"],
    strengths: ["security", "privacy"],
    features: {
      chat: true,
      threads: true,
      fileSharing: true,
      search: "unknown",
      notifications: "unknown",
      mobile: "unknown", // Element等クライアント側の対応
      sso: "unknown",
      voiceVideo: "unknown",
    },
  },

  // ---------------- Zapier ----------------
  n8n: {
    toolId: "n8n",
    saas: "zapier",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small", "medium", "large"],
    strengths: ["features", "customization", "active", "cost"],
    features: {
      visualWorkflow: true,
      scheduledTrigger: true,
      webhook: true,
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: true,
      templates: true,
    },
  },
  airflow: {
    toolId: "airflow",
    saas: "zapier",
    selfHost: true,
    managedCloud: "unknown", // サードパーティのマネージド提供あり。Apache本体としての提供ではない
    technicalLevel: 3,
    maintenanceLevel: 3,
    teamSize: ["medium", "large"],
    strengths: ["features", "active", "customization"],
    features: {
      visualWorkflow: false, // コードでDAGを定義する設計
      scheduledTrigger: true,
      webhook: "unknown",
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: true,
      templates: "unknown",
    },
  },
  kestra: {
    toolId: "kestra",
    saas: "zapier",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 2,
    maintenanceLevel: 2,
    teamSize: ["small", "medium", "large"],
    strengths: ["features", "active"],
    features: {
      visualWorkflow: "unknown",
      scheduledTrigger: true,
      webhook: true,
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: true,
      templates: true,
    },
  },
  activepieces: {
    toolId: "activepieces",
    saas: "zapier",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small", "medium"],
    strengths: ["usability", "cost", "active"],
    features: {
      visualWorkflow: true,
      scheduledTrigger: true,
      webhook: true,
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: "unknown",
      templates: true,
    },
  },
  "node-red": {
    toolId: "node-red",
    saas: "zapier",
    selfHost: true,
    managedCloud: false,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small"],
    strengths: ["customization", "cost", "usability"],
    features: {
      visualWorkflow: true,
      scheduledTrigger: true,
      webhook: true,
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: "unknown",
      templates: "unknown",
    },
  },
  prefect: {
    toolId: "prefect",
    saas: "zapier",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 2,
    maintenanceLevel: 2,
    teamSize: ["medium", "large"],
    strengths: ["features", "active"],
    features: {
      visualWorkflow: false,
      scheduledTrigger: true,
      webhook: "unknown",
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: true,
      templates: "unknown",
    },
  },
  temporal: {
    toolId: "temporal",
    saas: "zapier",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 3,
    maintenanceLevel: 3,
    teamSize: ["medium", "large"],
    strengths: ["features", "active", "customization"],
    features: {
      visualWorkflow: false, // コードでワークフローを書く設計
      scheduledTrigger: true,
      webhook: "unknown",
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: true,
      templates: "unknown",
    },
  },
  dagster: {
    toolId: "dagster",
    saas: "zapier",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 3,
    maintenanceLevel: 2,
    teamSize: ["medium", "large"],
    strengths: ["features", "active"],
    features: {
      visualWorkflow: false,
      scheduledTrigger: true,
      webhook: "unknown",
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: true,
      templates: "unknown",
    },
  },
  windmill: {
    toolId: "windmill",
    saas: "zapier",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 2,
    maintenanceLevel: 2,
    teamSize: ["small", "medium", "large"],
    strengths: ["features", "cost", "active"],
    features: {
      visualWorkflow: true,
      scheduledTrigger: true,
      webhook: true,
      apiIntegration: true,
      conditionalBranch: true,
      errorHandling: "unknown",
      templates: true,
    },
  },
  automatisch: {
    toolId: "automatisch",
    saas: "zapier",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small"],
    strengths: ["cost", "privacy", "usability"],
    features: {
      visualWorkflow: true,
      scheduledTrigger: true,
      webhook: true,
      apiIntegration: true,
      conditionalBranch: "unknown",
      errorHandling: "unknown",
      templates: "unknown",
    },
  },

  // ---------------- Trello ----------------
  focalboard: {
    toolId: "focalboard",
    saas: "trello",
    selfHost: true,
    managedCloud: false,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small", "medium"],
    strengths: ["cost", "privacy"],
    features: {
      board: true,
      task: true,
      assignee: true,
      dueDate: true,
      comments: true,
      automation: false,
      mobile: "unknown",
    },
  },
  wekan: {
    toolId: "wekan",
    saas: "trello",
    selfHost: true,
    managedCloud: false,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small", "medium"],
    strengths: ["cost", "privacy", "customization"],
    features: {
      board: true,
      task: true,
      assignee: true,
      dueDate: true,
      comments: true,
      automation: "unknown",
      mobile: true,
    },
  },
  planka: {
    toolId: "planka",
    saas: "trello",
    selfHost: true,
    managedCloud: false,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small"],
    strengths: ["usability", "cost", "privacy"],
    features: {
      board: true,
      task: true,
      assignee: true,
      dueDate: true,
      comments: true,
      automation: false,
      mobile: "unknown",
    },
  },
  kanboard: {
    toolId: "kanboard",
    saas: "trello",
    selfHost: true,
    managedCloud: false,
    technicalLevel: 0,
    maintenanceLevel: 0,
    teamSize: ["solo", "small"],
    strengths: ["cost", "privacy", "usability"],
    features: {
      board: true,
      task: true,
      assignee: true,
      dueDate: true,
      comments: true,
      automation: true,
      mobile: "unknown",
    },
  },

  // ---------------- Google Analytics ----------------
  umami: {
    toolId: "umami",
    saas: "google-analytics",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 0,
    teamSize: ["solo", "small", "medium", "large"],
    strengths: ["privacy", "cost", "usability", "active"],
    features: {
      pageviews: true,
      realtime: true,
      events: true,
      conversion: "unknown",
      privacyFriendly: true,
      selfhostable: true,
    },
  },
  plausible: {
    toolId: "plausible",
    saas: "google-analytics",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 0,
    teamSize: ["solo", "small", "medium", "large"],
    strengths: ["privacy", "usability", "active", "cost"],
    features: {
      pageviews: true,
      realtime: true,
      events: true,
      conversion: true,
      privacyFriendly: true,
      selfhostable: true,
    },
  },
  matomo: {
    toolId: "matomo",
    saas: "google-analytics",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small", "medium", "large"],
    strengths: ["features", "customization", "privacy"],
    features: {
      pageviews: true,
      realtime: true,
      events: true,
      conversion: true,
      privacyFriendly: true,
      selfhostable: true,
    },
  },
  fathom: {
    toolId: "fathom",
    saas: "google-analytics",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 1,
    maintenanceLevel: 0,
    teamSize: ["solo", "small", "medium"],
    strengths: ["privacy", "usability", "cost"],
    features: {
      pageviews: true,
      realtime: "unknown",
      events: "unknown",
      conversion: "unknown",
      privacyFriendly: true,
      selfhostable: true,
    },
  },
  goatcounter: {
    toolId: "goatcounter",
    saas: "google-analytics",
    selfHost: true,
    managedCloud: true,
    technicalLevel: 0,
    maintenanceLevel: 0,
    teamSize: ["solo", "small"],
    strengths: ["privacy", "cost", "usability"],
    features: {
      pageviews: true,
      realtime: "unknown",
      events: true,
      conversion: "unknown",
      privacyFriendly: true,
      selfhostable: true,
    },
  },
  ackee: {
    toolId: "ackee",
    saas: "google-analytics",
    selfHost: true,
    managedCloud: false,
    technicalLevel: 1,
    maintenanceLevel: 1,
    teamSize: ["solo", "small"],
    strengths: ["privacy", "cost"],
    features: {
      pageviews: true,
      realtime: "unknown",
      events: "unknown",
      conversion: "unknown",
      privacyFriendly: true,
      selfhostable: true,
    },
  },
};

export function getToolDiagnosisMeta(toolId: string): ToolDiagnosisMeta | undefined {
  return TOOL_DIAGNOSIS[toolId];
}

export function getToolIdsForSaas(saas: SaasId): string[] {
  return Object.values(TOOL_DIAGNOSIS)
    .filter((m) => m.saas === saas)
    .map((m) => m.toolId);
}
